"""edit users table

Revision ID: b225d53cf2a9
Revises: fae8d6e0b0e5
Create Date: 2026-03-12 15:47:52.587179

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b225d53cf2a9'
down_revision: Union[str, None] = 'fae8d6e0b0e5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('balance', sa.Integer(), nullable=False))
    op.add_column('users', sa.Column('rank_name', sa.String(), nullable=False))
    op.add_column('users', sa.Column('game_points', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'game_points')
    op.drop_column('users', 'rank_name')
    op.drop_column('users', 'balance')
    # ### end Alembic commands ###
