"""add grade in outfit users table

Revision ID: cdf44c1f5a0b
Revises: 43680828246d
Create Date: 2026-03-12 16:43:54.708615

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cdf44c1f5a0b'
down_revision: Union[str, None] = '43680828246d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('outfit_users', sa.Column('grade', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('outfit_users', 'grade')
    # ### end Alembic commands ###
