"""add date in user tasks table

Revision ID: f82f70c6d754
Revises: 6ed481629a91
Create Date: 2026-03-17 19:11:54.671560

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f82f70c6d754'
down_revision: Union[str, None] = '6ed481629a91'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_tasks', sa.Column('date', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_tasks', 'date')
    # ### end Alembic commands ###
